quarkus:
  console:
    color: true
  log:
    console:
      enable: true
      format: '%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n'
      level: TRACE
    category:
      "org.flywaydb.core.internal.sqlscript":
        level: FATAL
  flyway:
    migrate-at-start: true
    validate-on-migrate: true
    locations: "db/migration"
  hibernate-orm:
    database:
      generation: validate
